import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";

import type { paths } from "../schema"; // generated by openapi-typescript

export const BASE_URL = "http://127.0.0.1:8000";
export const client = createFetchClient<paths>({ baseUrl: BASE_URL });
export const api = createClient(client);
export const PAGE_SIZE = 25;
